Three new methods for native initialization flag
sentiance/react-native-sentiance pull request #150
Opened 2020-09-21 20:09 UTC by countcain

* enableNativeInitialization
   on Android: set the flag to sharedPreferences
   on iOS: create a plist file

* disableNativeInitialization
   on Android: clear the flag
   on iOS: delete the file

* isNativeInitializationEnabled
   on Andorid: check flag value
   on iOS: does file exist

Tested [on the example app](https://github.com/sentiance/react-native-sentiance-example/compare/native-initialization-flag?expand=1).

2020-09-23 11:56 UTC, sebouh00 requested changes
I suggest making all 3 methods available natively via the helper as well, since enabling and disabling native initialization may be a change the native code might want to make too.

2020-09-23 11:56 UTC, sebouh00 commented on ios/RNSentiance.m
> +    NSMutableDictionary *restoredValues = [[NSMutableDictionary alloc] initWithContentsOfFile:path];
The data inside the file doesn't seem to be necessary. Can we get rid of the below logic and simple use the file's existence as an indicator? If it exists, doesn't even have to be a plist file, it signifies that native init is enabled. The file name could be something like "initialize_natively".

2020-09-23 23:52 UTC, countcain commented on ios/RNSentiance.m
> +    NSString *sentianceDir = [docDir stringByAppendingPathComponent:@"sentiance"];
Changed to `RNSentiance`

2020-09-23 23:53 UTC, countcain commented on ios/RNSentiance.m
> +    NSMutableDictionary *restoredValues = [[NSMutableDictionary alloc] initWithContentsOfFile:path];
Removed the file's content. indeed it is not necessary. And rename the file to `rnsentiance_initialize_natively`

2020-09-29 07:01 UTC, sebouh00 requested changes

2020-09-30 03:04 UTC, countcain commented on ios/RNSentiance.h
> +- (void) disableSDKNativeInitialization:(RCTPromiseResolveBlock _Nullable)resolve rejecter:(RCTPromiseRejectBlock _Nullable)reject;
The name here cannot be the same as the function name that exposes to react-native.

We already have 
`RCT_EXPORT_METHOD(disableNativeInitialization:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)`

Adding another 
`- (void)disableSDKNativeInitialization:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject `
will cause an `Duplicate declaration of method 'disableNativeInitialization:rejecter:'` error.

This is the same as our existing init methods. `initSDK` for native code and `RCT_EXPORT_METHOD(init ...)` for react-native.

The function name can be duplicated only if they have different parameters, like method overloading in java.

2020-09-30 03:15 UTC, countcain commented on ios/RNSentiance.m
> +        } else if (resolve) {
Yep, corrected. It is unlikely that resolve is not `nil` but reject is. But in case the function is called that way.

2020-09-30 03:24 UTC, countcain commented on ios/RNSentiance.m
> +    NSString *sentianceDir = [docDir stringByAppendingPathComponent:@"RNSentiance"];
Added.

2020-09-30 08:14 UTC, sebouh00 approved these changes

2020-10-01 04:50 UTC, countcain commented on ios/RNSentiance.m
> +    NSString *docDir = [[fileManager URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] lastObject].path;
Sorry, I don't quite understand what you mean by a separate class. Like a new header file ```RNSentianceFile.h``` with a new ```RNSentianceFile.m```?

In that case, will the integration import two headers? as:
```
#import "RNSentiance.h" // Import Sentiance React Native bridge module
#import "RNSentianceFile.h" // Import Sentiance React Native bridge file module
```

IMO I don't see the necessity to do this. Might confuse developers.

2020-10-01 08:07 UTC, ralf601 commented on ios/RNSentiance.m
> +    NSString *docDir = [[fileManager URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] lastObject].path;
It's an internal logic how we read / write from file so for integration it will not be required to import `RNSentianceFile.h`, this will only be needed in `RNSentiance.m`.

What i meant is 

```
- (void)enableSDKNativeInitialization:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject {
   
    resolve([nativeInitConfig exists])
    // all code related to read / write file can be moved to the config class.
}

```

2020-10-05 20:00 UTC, countcain commented on ios/RNSentiance.m
> +    NSString *docDir = [[fileManager URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] lastObject].path;
Make sense. Updated

2020-10-06 13:48 UTC, ralf601 approved these changes

2020-10-07 20:55 UTC, merged